steps:
  - uses: actions/checkout@v4

  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v4
    with:
      node-version: ${{ matrix.node-version }}
      cache: "npm"
      cache-dependency-path: "api-productos-mongo/package-lock.json"

  - name: Install dependencies
    run: npm ci
    working-directory: api-productos-mongo

  - name: Run tests
    run: npm test
    working-directory: api-productos-mongo
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
